### PR TITLE
rework plugin

### PR DESCRIPTION
**Pull request by timogoebel**
This PR is a rework of this plugin.

It adds Host Status, Multiple Actions, Tests and Rails 4 compatibility.

### CODE REVIEW

**Comment by iakovgan** [comment]
Great job!

**Comment by timogoebel** [comment]
@iakovgan : This seems rather unmaintained. I'd like to move this to theforeman.org, start packaging and start maintaining it. Would that be ok with you?

**Comment by iakovgan** [comment]
Yes please! I am happy if it will be useful.

**Comment by iakovgan** [comment]
I have also foreman-hieralookup and compute- resource-statistics plugins that are not maintained as they deserve.

**Comment by timogoebel** [comment]
@iakovgan : One thing at a time. Could you give me admin access to this repo? That's required to start the transfer...

**Pull request merged**
