### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by ohadlevy**
Hi,

I've started reviewing the plugin, and starting refactoring, this is an initial set of suggestions

thanks!

### CODE REVIEW

**Comment by iakovgan** [comment]
Awsome thanks! We will review this asap.

**Comment by ohadlevy** [comment]
@iakovgan @nagarjuna I would suggest to review each commit, its probably easier to digest.. if its too much, i don't mind breaking down to multiple pull requests, but would need to make sure at least the initial one is merged as it blocks the rest.

**Comment by nagarjuna** [comment]
@ohadlevy  How can we use gem dependent(bootstrap datepicker gem) in RPM package ?

**Comment by nagarjuna** [comment]
@ohadlevy So you are suggesting to make datepicker gem as dependent and need to bundle as separate  RPM(datepicker is one RPM and foreman_expire_hosts is another RPM) ?

**Comment by ohadlevy** [comment]
@nagarjuna exactly

**Comment by nagarjuna** [comment]
@ohadlevy OK will merge your changes and build gem, later will bundle RPM packages(both bootstrap-datepicker and foreman_expire_hosts). Thanks for your suggestions :)

**Pull request merged**
